# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xunililak/Code/Projects/1-VulkanEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xunililak/Code/Projects/1-VulkanEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xunililak/Code/Projects/1-VulkanEngine/CMakeFiles /home/xunililak/Code/Projects/1-VulkanEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xunililak/Code/Projects/1-VulkanEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Application

# Build rule for target.
Application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Application
.PHONY : Application

# fast build rule for target.
Application/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/build
.PHONY : Application/fast

#=============================================================================
# Target rules for targets named neko

# Build rule for target.
neko: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neko
.PHONY : neko

# fast build rule for target.
neko/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/neko.dir/build.make src/CMakeFiles/neko.dir/build
.PHONY : neko/fast

#=============================================================================
# Target rules for targets named neko_utils

# Build rule for target.
neko_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neko_utils
.PHONY : neko_utils

# fast build rule for target.
neko_utils/fast:
	$(MAKE) $(MAKESILENT) -f src/utils/CMakeFiles/neko_utils.dir/build.make src/utils/CMakeFiles/neko_utils.dir/build
.PHONY : neko_utils/fast

#=============================================================================
# Target rules for targets named neko_engine

# Build rule for target.
neko_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neko_engine
.PHONY : neko_engine

# fast build rule for target.
neko_engine/fast:
	$(MAKE) $(MAKESILENT) -f src/engine/CMakeFiles/neko_engine.dir/build.make src/engine/CMakeFiles/neko_engine.dir/build
.PHONY : neko_engine/fast

#=============================================================================
# Target rules for targets named neko_events

# Build rule for target.
neko_events: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neko_events
.PHONY : neko_events

# fast build rule for target.
neko_events/fast:
	$(MAKE) $(MAKESILENT) -f src/events/CMakeFiles/neko_events.dir/build.make src/events/CMakeFiles/neko_events.dir/build
.PHONY : neko_events/fast

#=============================================================================
# Target rules for targets named neko_renderer

# Build rule for target.
neko_renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neko_renderer
.PHONY : neko_renderer

# fast build rule for target.
neko_renderer/fast:
	$(MAKE) $(MAKESILENT) -f src/renderer/CMakeFiles/neko_renderer.dir/build.make src/renderer/CMakeFiles/neko_renderer.dir/build
.PHONY : neko_renderer/fast

#=============================================================================
# Target rules for targets named neko_threads

# Build rule for target.
neko_threads: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neko_threads
.PHONY : neko_threads

# fast build rule for target.
neko_threads/fast:
	$(MAKE) $(MAKESILENT) -f src/threads/CMakeFiles/neko_threads.dir/build.make src/threads/CMakeFiles/neko_threads.dir/build
.PHONY : neko_threads/fast

Application.o: Application.cpp.o
.PHONY : Application.o

# target to build an object file
Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Application.cpp.o
.PHONY : Application.cpp.o

Application.i: Application.cpp.i
.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s
.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Application.cpp.s
.PHONY : Application.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Application"
	@echo "... neko"
	@echo "... neko_engine"
	@echo "... neko_events"
	@echo "... neko_renderer"
	@echo "... neko_threads"
	@echo "... neko_utils"
	@echo "... Application.o"
	@echo "... Application.i"
	@echo "... Application.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

