#ifndef VKW_INTERFACE_TINY_OBJ_LOADER_HPP
#define VKW_INTERFACE_TINY_OBJ_LOADER_HPP

// #ifndef TINYOBJLOADER_IMPLEMENTATION
// #define TINYOBJLOADER_IMPLEMENTATION
// #include <tiny_obj_loader.h>
// #endif /* TINYOBJLOADER_IMPLEMENTATION */

#include <tiny_obj_loader.h>

#endif /* VKW_INTERFACE_TINY_OBJ_LOADER_HPP */