#ifndef HDG_RENDERER_GENRIC_VULKANMODULES_HPP
#define HDG_RENDERER_GENRIC_VULKANMODULES_HPP

#include "Vulkan/Basic/Context.hpp"
#include "Vulkan/Basic/Extensions.hpp"
#include "Vulkan/Basic/Framebuffers.hpp"
#include "Vulkan/Basic/Instance.hpp"
#include "Vulkan/Basic/Surface.hpp"
#include "Vulkan/Basic/Swapchain.hpp"
#include "Vulkan/Basic/Synchronization.hpp"
#include "Vulkan/Basic/Window.hpp"
#include "Vulkan/Commands/Commands.hpp"
#include "Vulkan/Devices/Logical.hpp"
#include "Vulkan/Devices/Physical.hpp"
#include "Vulkan/Devices/Queue.hpp"
#include "Vulkan/Pipelines/Compute.hpp"
#include "Vulkan/Pipelines/Graphics.hpp"
#include "Vulkan/Pipelines/PipelineCache.hpp"
#include "Vulkan/Pipelines/PipelineLayout.hpp"
#include "Vulkan/Pipelines/RenderPass.hpp"
#include "Vulkan/Pipelines/ShaderModules.hpp"
#include "Vulkan/Pipelines/ShaderObjects.hpp"
#include "Vulkan/Resources/Buffers.hpp"
#include "Vulkan/Resources/Descriptors.hpp"
#include "Vulkan/Resources/Images.hpp"
#include "Vulkan/Resources/ResourceUtils.hpp"
#include "Vulkan/Resources/Sampler.hpp"
#include "Vulkan/Resources/UsageSpecific.hpp"

#endif /* HDG_RENDERER_GENRIC_VULKANMODULES_HPP */